name: Continuous integration
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: gradle:jdk11
    steps:
      - uses: actions/checkout@v2
      - run: |
          ./gradlew jar
